name: build

on:
  push:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run npm build
        run: npm run build
        working-directory: frontend

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/dist
          CLEAN: true
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: docker build --pull --rm -f "backend/Dockerfile" -t ghcr.io/littletitan/school-websites:latest "backend"
      - run: docker push ghcr.io/littletitan/school-websites:latest